# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc89c9b712febabf857c3abc71900cc131b8e6d3758797c566188690131848abe65bd1c1182fa92d25c9ee9e786704dbb04094356b765a4ee6d3ee2af0041459

test:
  secret_key_base: e836cc5841a10dd4879a8cd8553c234a6d456f57d7c30fd395ee8899491e01aaef472f8d33da923b99621a03fefd5533f4f7c2e345e06c626f474918fcf32d89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
